name: Build IPF Gazelle with Maven

on: [push, pull_request]

env:
  MAVEN_OPTS: -Xmx1024m

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
    name: Java ${{ matrix.java }} build
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      #   Publish somewhere
      #   Maybe in a separate action file
      #   for publishing/releasing: https://github.com/marketplace/actions/action-maven-publish
      #   see https://github.com/organizations/oehf/settings/secrets/actions
      - name: Deploy to Sonatype Snapshot Repo
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}